// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameApp = "app"

// App 用户表
type App struct {
	ID                string         `gorm:"column:id;primaryKey;comment:Uuid md5 16位" json:"id"` // Uuid md5 16位
	UserID            string         `gorm:"column:user_id;not null" json:"user_id"`
	Name              string         `gorm:"column:name;not null;comment:appname" json:"name"`                               // appname
	ShortName         string         `gorm:"column:short_name;not null;comment:短名称" json:"short_name"`                       // 短名称
	Description       string         `gorm:"column:description;not null;comment:描述" json:"description"`                      // 描述
	Icons             string         `gorm:"column:icons;not null;comment:Icon" json:"icons"`                                // Icon
	AppURL            string         `gorm:"column:app_url;not null;comment:App实际地址" json:"app_url"`                         // App实际地址
	AppDevName        string         `gorm:"column:app_dev_name;not null;comment:开发者名称" json:"app_dev_name"`                 // 开发者名称
	AppRateNum        float64        `gorm:"column:app_rate_num;not null;comment:评分" json:"app_rate_num"`                    // 评分
	AppRateCount      int64          `gorm:"column:app_rate_count;not null;comment:评分人数" json:"app_rate_count"`              // 评分人数
	AppInstallCount   int64          `gorm:"column:app_install_count;not null;comment:安装人数" json:"app_install_count"`        // 安装人数
	AppSafeAge        int64          `gorm:"column:app_safe_age;not null;comment:适配年龄" json:"app_safe_age"`                  // 适配年龄
	AppScreen         string         `gorm:"column:app_screen;not null;comment:五图" json:"app_screen"`                        // 五图
	IosJump           int32          `gorm:"column:ios_jump;not null;comment:IOS是否跳转1跳转0不跳转" json:"ios_jump"`                // IOS是否跳转1跳转0不跳转
	AppDescription    string         `gorm:"column:app_description;not null;comment:应用介绍" json:"app_description"`            // 应用介绍
	Status            bool           `gorm:"column:status;not null;comment:状态，1:下架，0:在架" json:"status"`                      // 状态，1:下架，0:在架
	ScreenOrientation bool           `gorm:"column:screen_orientation;not null;comment:0:竖屏，1:横屏" json:"screen_orientation"` // 0:竖屏，1:横屏
	PromotionURL      string         `gorm:"column:promotion_url;not null;comment:推广链接" json:"promotion_url"`                // 推广链接
	CreatedAt         time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Iframe            bool           `gorm:"column:iframe;not null;comment:是否打开iframe1打开0关闭" json:"iframe"`                        // 是否打开iframe1打开0关闭
	Remarks           string         `gorm:"column:remarks;comment:备注" json:"remarks"`                                             // 备注
	InstallTemplate   bool           `gorm:"column:install_template;not null;default:1;comment:0:竖屏，1:横屏" json:"install_template"` // 0:竖屏，1:横屏
	AnySiteInstall    bool           `gorm:"column:any_site_Install;not null;comment:点击任意位置安装应用:0否1是" json:"any_site_Install"`     // 点击任意位置安装应用:0否1是
	SiteModify        int32          `gorm:"column:site_modify;not null;comment:网络地址是否允许修改，1允许0不允许" json:"site_modify"`            // 网络地址是否允许修改，1允许0不允许
	DataBuriedPoint   string         `gorm:"column:data_buried_point;comment://数据埋点" json:"data_buried_point"`                     // //数据埋点
	BuriedPointID     string         `gorm:"column:buried_point_id;comment://记录id" json:"buried_point_id"`                         // //记录id
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
