// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAppSubUser = "app_sub_user"

// AppSubUser mapped from table <app_sub_user>
type AppSubUser struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增id" json:"id"` // 自增id
	AppID     string         `gorm:"column:app_id;not null" json:"app_id"`
	UserID    string         `gorm:"column:user_id;not null" json:"user_id"`
	SubInfo   string         `gorm:"column:sub_info;not null" json:"sub_info"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName AppSubUser's table name
func (*AppSubUser) TableName() string {
	return TableNameAppSubUser
}
