// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        string         `gorm:"column:id;primaryKey;comment:Uuid md5 16位" json:"id"` // Uuid md5 16位
	Email     string         `gorm:"column:email;not null;comment:邮箱，账户" json:"email"`    // 邮箱，账户
	Password  string         `gorm:"column:password;not null;comment:密码" json:"password"` // 密码
	Money     float64        `gorm:"column:money;not null;comment:余额" json:"money"`       // 余额
	Rate      float64        `gorm:"column:rate;not null;default:0.080" json:"rate"`
	Utype     bool           `gorm:"column:utype;not null;comment:0:预付费，1:后付费" json:"utype"` // 0:预付费，1:后付费
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
